version: '3'
services:
  frontend:
    build:
      context: .
    container_name: first_logistics
    hostname: first_logistics
    restart: always
    ports:
      - 8080:80
    
networks:
  default:
    driver: bridge

