export {
  getOrdersList,
  getOrdersListSlice,
  addOrder,
  addOrderSlice,
  UpdateOrder,
  UpdateOrderSlice,
  getCategoriesList,
  getCategoriesListSlice,
  getDeliveryCompanyList,
  getDeliveryCompanyListSlice,
  getOrderDetails,
  getOrderDetailsSlice,
  updateOrderStatus,
  updateOrderStatusSlice,
} from './orders'
